### ISSUE TITLE
Firefox errors get slightly truncated

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#114]
Glenn observed that the errors I was getting when ritualEngine crashed were weirdly truncated. I think this is just a firefox issue. In chrome I get the top-level error message.

i.e. instead of this:

```
TwilioError: Room not found
    at RoomNotFoundError.TwilioError (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:24655:23)
    at new RoomNotFoundError (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:23851:119)
    at createTwilioError (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:23397:36)
    at TwilioConnection.handleMessage (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:15640:28)
    at TwilioConnection.emit (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:29140:5)
    at TwilioConnection._handleMessage (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:18955:12)
    at WebSocket.<anonymous> (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:18807:20)
```

I got this:

```
TwilioError@https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:24653:124
RoomNotFoundError@https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:23851:119
createTwilioError@https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:23397:36
handleMessage@https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:15640:28
emit@https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:29140:17
_handleMessage@https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:18955:12
_connect/<@https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.js:18807:20
```

**Comment by taymonbeal** [comment]
Can you see if this is still an issue with Sentry?

**Comment by taymonbeal** [comment]
Not high enough priority if even still a thing at all.
