### ISSUE TITLE
KeyError in ritual.clients

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#155]
```
500 Error
status?clientId=DYg8t18BdwKMn7Qch3FrM5nG4ZspYwqVkWaLQjfMpFM&have=2&subhave=-1
KeyError
'DYg8t18BdwKMn7Qch3FrM5nG4ZspYwqVkWaLQjfMpFM'

Traceback (most recent call last):
  File "/home/ubuntu/ritualEngine/core.py", line 153, in errorHandler
    return await handler(request)
  File "/home/ubuntu/ritualEngine/widgetry.py", line 54, in status
    ritual.clients[clientId].lastSeen = datetime.now()
KeyError: 'DYg8t18BdwKMn7Qch3FrM5nG4ZspYwqVkWaLQjfMpFM'
```

I'm guessing that this _probably_ is the result of the server being restarted, so we can postpone fixing it for now, but it would be better to handle this gracefully so that we can be sure.

**Comment by dspeyer** [comment]
Yes, this is the result of the server being restarted.

**Comment by taymonbeal** [comment]
Not going to worry about this for Solstice.
