### ISSUE TITLE
Bug: Crashing after many refreshes.

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#79]
Possibly relatedly to https://github.com/dspeyer/ritualEngine/issues/78:

When I refresh a whole bunch of times, I eventually got a large number of avatars... until suddenly I got this error instead:

```
Traceback (most recent call last):
  File "/Users/raymondarnold/Documents/ritualEngine/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/raymondarnold/Documents/ritualEngine/venv/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/Users/raymondarnold/Documents/ritualEngine/widgetry.py", line 108, in status
    results['clients'] = [ { 'id':k, 'room':v.room, 'hj':hasattr(v,'jpg') }
  File "/Users/raymondarnold/Documents/ritualEngine/widgetry.py", line 108, in <listcomp>
    results['clients'] = [ { 'id':k, 'room':v.room, 'hj':hasattr(v,'jpg') }
AttributeError: 'struct' object has no attribute 'room'
```

**Comment by taymonbeal** [comment]
I think this was fixed by b5f47d60fd820e5862b67bd335cf084aff19f394.
