### ISSUE TITLE
TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#89]
Happened on SolsticeStressTest, I _think_ when Taymon switched from partaking to leading. Happened for me and Glenn.

```
TypeError: Cannot read property 'addEventListener' of null
    at BucketSinging.init_video (https://secularsolsticebeta.com/widgets/BucketSinging.js:192:12)
    at new BucketSinging (https://secularsolsticebeta.com/widgets/BucketSinging.js:164:12)
    at Object.success (https://secularsolsticebeta.com/test/partake:290:49)
```

**Comment by taymonbeal** [comment]
I think I fixed this in af889f491a7c883c57c17c8cc474a39ee3d51bb4.
